stellaris_database/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from store import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', views.home, name="home"),
    path('accounts/', include('allauth.urls')),
]

# To display images
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from store.forms import LoginForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'store'

urlpatterns = [
    #URL for Content
    path('', views.home, name="home"),
    path('location/', views.location_view, name="location"),
    path('gallery/', views.gallery_view, name="gallery"),
    path('about-us/', views.aboutus_view, name="about-us"),
    
    # URL for Cart and Checkout
    path('add-to-cart/', views.add_to_cart, name="add-to-cart"),
    path('add-to-favorites/', views.add_to_favorite, name="add-to-favorite"),
    path('remove-cart/<int:cart_id>/', views.remove_cart, name="remove-cart"),
    path('plus-cart/<int:cart_id>/', views.plus_cart, name="plus-cart"),
    path('minus-cart/<int:cart_id>/', views.minus_cart, name="minus-cart"),
    path('cart/', views.cart, name="cart"),
    path('favorites/', views.favorite_view, name='favorites'),
    path('remove-favorites/<int:favorites_id>/', views.remove_favorites, name="remove-favorites"),
    path('orders/', views.orders, name="orders"),
    path('checkout/', views.checkout, name="checkout"),

    #URL for Products
    path('product/<slug:slug>/', views.detail, name="product-detail"),
    path('categories/', views.all_categories, name="all-categories"),
    path('<slug:slug>/', views.category_products, name="category-products"),



    # URL for Authentication
    path('accounts/login/', auth_views.LoginView.as_view(template_name='account/login.html', authentication_form=LoginForm), name="login"),
    path('accounts/profile/', views.profile, name="profile"),
    path('accounts/add-address/', views.DeliveryView.as_view(), name="add-address"),
    path('accounts/remove-address/<int:id>/', views.remove_address, name="remove-address"),
    path('accounts/add-reservation/', views.ReservationView.as_view(), name="reservation"),
    path('accounts/remove-reservation/<int:id>/', views.remove_reservation, name="remove-reservation"),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='store:login'), name="logout"),

    path('accounts/password-change/', auth_views.PasswordChangeView.as_view(template_name='account/password_change.html', form_class=PasswordChangeForm, success_url='/accounts/password-change-done/'), name="password-change"),
    path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'), name="password-change-done") ,

    path('accounts/password-reset/', auth_views.PasswordResetView.as_view(template_name='account/password_reset.html', form_class=PasswordResetForm, success_url='/accounts/password-reset/done/'), name="password-reset"), # Passing Success URL to Override default URL, also created password_reset_email.html due to error from our app_name in URL
    path('accounts/password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'), name="password_reset_done"),
    path('accounts/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html', form_class=SetPasswordForm, success_url='/accounts/password-reset-complete/'), name="password_reset_confirm"), # Passing Success URL to Override default URL
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), name="password_reset_complete"),    
]

store/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.models import User
from tomlkit import datetime
from store.forms import DeliveryForm, ReservationForm
from .models import *
from django.contrib import messages
from django.views import View
import decimal
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.http import HttpResponseRedirect

# Create your views here.

def home(request):
    categories = Category.objects.filter(is_active=True, is_featured=True)[:3]
    products = Product.objects.filter(is_active=True, is_featured=True)[:8]
    not_products = Product.objects.filter(is_active=False, is_featured=True)[:8]
    context = {
        'categories': categories,
        'products': products,
        'not_products': not_products,
    }
    return render(request, 'store/index.html', context)

def detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    not_products = Product.objects.filter(is_active=False, id=product.id)
    related_products = Product.objects.exclude(id=product.id).filter(is_active=True, category=product.category)
    context = {
        'product': product,
        'related_products': related_products,
        'not_products': not_products,
    }
    return render(request, 'store/detail.html', context)

def all_categories(request):
    categories = Category.objects.filter(is_active=True)
    return render(request, 'store/categories.html', {'categories':categories})

def category_products(request, slug):
    category = get_object_or_404(Category, slug=slug)
    products = Product.objects.filter(is_active=True, category=category)
    categories = Category.objects.filter(is_active=True)
    not_products = Product.objects.filter(is_active=False, category=category)
    context = {
        'category': category,
        'products': products,
        'categories': categories,
        'not_products': not_products,
    }
    return render(request, 'store/category_products.html', context)

def gallery_view(request):
    gallery = Gallery.objects.all()
    context = {
        'gallery': gallery,
    }
    return render(request, 'store/gallery.html', context)

def location_view(request):
    return render(request, 'store/location.html')

def aboutus_view(request):
    return render(request, 'store/about_us.html')

@login_required
def profile(request):
    delivery_information = DeliveryInformation.objects.filter(user=request.user)
    orders = Order.objects.filter(user=request.user)
    reservations = Reservation.objects.filter(user=request.user)
    order_item = OrderItem.objects.filter(user=request.user)
    return render(request, 'account/profile.html', {'delivery_information':delivery_information, 'orders':orders, 'reservations':reservations,'order_items':order_item})

@method_decorator(login_required, name='dispatch')
class DeliveryView(View):
    def get(self, request):
        form = DeliveryForm()
        return render(request, 'account/add_address.html', {'form': form})

    def post(self, request):
        form = DeliveryForm(request.POST)
        if form.is_valid():
            user=request.user
            recipient_name = form.cleaned_data['recipient_name']
            phone_number = form.cleaned_data['phone_number']
            telephone_number = form.cleaned_data['telephone_number']
            barangay = form.cleaned_data['barangay']
            landmark = form.cleaned_data['landmark']
            street_name = form.cleaned_data['street_name']
            city = form.cleaned_data['city']
            reg = DeliveryInformation(user=user, recipient_name=recipient_name, phone_number=phone_number,telephone_number=telephone_number,barangay=barangay,landmark=landmark,street_name=street_name,city=city)
            reg.save()
            messages.success(request, "New Delivery Address Added Successfully.")
        return redirect('store:home')

@method_decorator(login_required, name='dispatch')
class ReservationView(View):
    def get(self, request):
        form = ReservationForm()
        return render(request, 'store/reservation.html', {'form': form})
    
    def post(self, request):
        form = ReservationForm(request.POST)
        if form.is_valid():
            user=request.user
            phone_number = form.cleaned_data['phone_number']
            telephone_number = form.cleaned_data['telephone_number']
            pax = form.cleaned_data['pax']
            event_name = form.cleaned_data['event_name']
            event_type = form.cleaned_data['event_type']
            event_time = form.cleaned_data['event_time']
            event_time_end = form.cleaned_data['event_time_end']
            event_date = form.cleaned_data['event_date']
            remarks = form.cleaned_data['remarks']
            reg = Reservation(user=user, phone_number=phone_number,telephone_number=telephone_number, pax=pax, event_name=event_name, event_type=event_type, event_time=event_time,event_time_end=event_time_end ,event_date=event_date, remarks=remarks)
            reg.save()
            messages.success(request, "Reservation Added Successfully!")
        else:
            messages.error(request, "The Scheduled Date Is Already Taken!")
        return redirect('store:profile')

@login_required
def remove_address(request, id):
    a = get_object_or_404(DeliveryInformation, user=request.user, id=id)
    a.delete()
    messages.success(request, "Delivery Address removed.")
    return redirect('store:profile')

@login_required
def remove_reservation(request, id):
    r = get_object_or_404(Reservation, user=request.user, id=id)
    r.delete()
    messages.success(request, "Reservation removed.")
    return redirect('store:profile')

@login_required
def add_to_cart(request):
    user = request.user
    product_id = request.GET.get('prod_id')
    product = get_object_or_404(Product, id=product_id)

    item_already_in_cart = Cart.objects.filter(product=product_id, user=user)
    if item_already_in_cart:
        cp = get_object_or_404(Cart, product=product_id, user=user)
        cp.quantity += 1
        cp.save()
    else:
        Cart(user=user, product=product).save()
    messages.success(request, 'Added to Cart successfully!')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def cart(request):
    user = request.user
    cart_products = Cart.objects.filter(user=user)


    amount = decimal.Decimal(0)
    delivery_fee = decimal.Decimal(50)

    cp = [p for p in Cart.objects.all() if p.user==user]
    if cp:
        for p in cp:
            temp_amount = (p.quantity * p.product.price)
            amount += temp_amount

    # Customer Addresses
    delivery_addresses = DeliveryInformation.objects.filter(user=user)

    context = {
        'cart_products': cart_products,
        'amount': amount,
        'delivery_fee': delivery_fee,
        'total_amount': amount + delivery_fee,
        'delivery_addresses': delivery_addresses,
    }
    return render(request, 'store/cart.html', context)

@login_required
def remove_cart(request, cart_id):
    if request.method == 'GET':
        c = get_object_or_404(Cart, id=cart_id)
        c.delete()
        messages.success(request, "Item removed from Cart.")
    return redirect('store:cart')

@login_required
def remove_favorites(request, favorites_id):
    if request.method == 'GET':
        c = get_object_or_404(Favorites, id=favorites_id)
        c.delete()
        messages.error(request, "Item remove from Favorites.")
    return redirect('store:favorites')

@login_required
def plus_cart(request, cart_id):
    if request.method == 'GET':
        cp = get_object_or_404(Cart, id=cart_id)
        cp.quantity += 1
        cp.save()
    messages.success(request, "Item quantity is now added!")
    return redirect('store:cart')

@login_required
def minus_cart(request, cart_id):
    if request.method == 'GET':
        cp = get_object_or_404(Cart, id=cart_id)
        if cp.quantity == 1:
            messages.success(request, 'Item is now deleted from cart!')
            cp.delete()
        else:
            cp.quantity -= 1
            messages.success(request, 'Item is removed by 1')
            cp.save()
    return redirect('store:cart')

@login_required
def favorite_view(request):
    user = request.user
    favorite_products = Favorites.objects.filter(user=user)
    context = {
        'favorite_products': favorite_products,
    }
    return render(request, 'store/favorites.html', context)

@login_required
def add_to_favorite(request):
    user = request.user
    product_id = request.GET.get('prod_id')
    product = get_object_or_404(Product, id=product_id)

    item_already_in_favorite = Favorites.objects.filter(product=product_id, user=user)
    if item_already_in_favorite:
        messages.error(request, 'Item is already in favorites!')
    else:
        messages.add_message(request, messages.SUCCESS, 'Item is now added in favorites!')
        Favorites(user=user, product=product).save()

    return redirect('store:favorites')

@login_required
def checkout(request):
    user = request.user
    address_id = request.GET.get('address')
    address = get_object_or_404(DeliveryInformation, id=address_id)
    amount = decimal.Decimal(0)
    delivery_fee = decimal.Decimal(50)

    cp = [p for p in Cart.objects.all() if p.user==user]
    if cp:
        for p in cp:
            temp_amount = (p.quantity * p.product.price)
            amount += temp_amount

    order = Order.objects.create(
        user=user,
        address=address,
        total_price = amount+delivery_fee
    )
    order.save()
    cart = Cart.objects.filter(user=user)
    for c in cart:
        OrderItem(invoice_no='INV-'+str(order.id),user=user,product=c.product,quantity=c.quantity,price=c.quantity*c.product.price).save()
    

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

    {% block content %}
    <script>
      function confirmation()
      {
        alert("You will be given a reciept upon ordering, please keep your phone number open thank you!");
      }
    </script>
      <div class="container">
        <!-- HERO SECTION-->
        <section class="py-5 bg-light">
          <div class="container">
            <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
              <div class="col-lg-6">
                <h1 class="h2 text-uppercase mb-0">Cart</h1>
              </div>
              <div class="col-lg-6 text-lg-right">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb justify-content-lg-end mb-0 px-0">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Cart</li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </section>

        {% if cart_products %}
        <section class="py-5">
          <h2 class="h5 text-uppercase mb-4">MY CART</h2>


          <div class="row">
            <div class="col-lg-8 mb-4 mb-lg-0">
              <!-- CART TABLE-->
              <div class="table-responsive mb-4">
                <table class="table">
                  <thead class="bg-light">
                    <tr>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Product</strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Price</strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Quantity</strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Total</strong></th>
                      <th class="border-0" scope="col"> </th>
                    </tr>
                  </thead>
                  <tbody>

                    {% for cart_product in cart_products %}
                    <tr>
                      <th class="pl-0 border-0" scope="row">
                        <div class="media align-items-center">

                          {% if cart_product.product.product_image %}
                            <a class="reset-anchor d-block animsition-link" href="{% url 'store:product-detail' cart_product.product.slug %}"><img src="{{cart_product.product.product_image.url}}" alt="{{cart_product.product.title}}" width="70"/></a>
                          {% else %}
                            <a class="reset-anchor d-block animsition-link" href="{% url 'store:product-detail' cart_product.product.slug %}"><img src="{% static 'img/product-detail-3.jpg' %}" alt="{{cart_product.product.title}}" width="70"/></a>
                          {% endif %}

                          <div class="media-body ml-3"><strong class="h6"><a class="reset-anchor animsition-link" href="{% url 'store:product-detail' cart_product.product.slug %}">{{cart_product.product.title}}</a></strong></div>
                        </div>
                      </th>
                      <td class="align-middle border-0">
                        <p class="mb-0 small">P{{cart_product.product.price}}</p>
                      </td>
                      <td class="align-middle border-0">
                        <div class="border d-flex align-items-center justify-content-between px-3"><span class="small text-uppercase text-gray headings-font-family">Quantity</span>
                          <div class="quantity">
                            <a href="{% url 'store:minus-cart' cart_product.id %}" class="dec-btn p-0 ml-2"><i class="fas fa-minus"></i></a>
                            {% comment %} <button class="dec-btn p-0"><i class="fas fa-caret-left"></i></button> {% endcomment %}
                            <input class="form-control form-control-sm border-0 shadow-0 p-0" type="text" value="{{cart_product.quantity}}"/>
                            {% comment %} <button class="inc-btn p-0"><i class="fas fa-caret-right"></i></button> {% endcomment %}
                            <a href="{% url 'store:plus-cart' cart_product.id %}" class="inc-btn p-0"><i class="fas fa-plus"></i></a>
                          </div>
                        </div>
                      </td>
                      <td class="align-middle border-0">
                        <p class="mb-0 small">P{{cart_product.total_price|intcomma}}</p>
                      </td>
                      <td class="align-middle border-0"><a class="reset-anchor" href="{% url 'store:remove-cart' cart_product.id %}"><i class="fas fa-trash-alt small text-muted"></i></a></td>
                    </tr>
                    {% endfor %}

                  </tbody>
                </table>
              </div>
              <!-- CART NAV-->
              <div class="bg-light px-4 py-3">
                <div class="row align-items-center text-center">
                  <div class="col-md-6 mb-3 mb-md-0 text-md-left"><a class="btn btn-link p-0 text-dark btn-sm" href="{% url 'store:home' %}"><i class="fas fa-long-arrow-alt-left mr-2"> </i>Continue shopping</a></div>
                </div>
              </div>
            </div>
            <!-- ORDER TOTAL-->
            <div class="col-lg-4">
              <div class="card border-0 rounded-0 p-lg-4 bg-light">
                <div class="card-body">
                  <h5 class="text-uppercase mb-4">Cart total</h5>
                  <ul class="list-unstyled mb-0">
                    <li class="d-flex align-items-center justify-content-between"><strong class="text-uppercase small font-weight-bold">Subtotal</strong><span class="text-muted small">P{{amount|intcomma}}</span></li>
                    <li class="d-flex align-items-center justify-content-between"><strong class="text-uppercase small font-weight-bold">Delivery Charge</strong><span class="text-muted small">+ P{{delivery_fee}}</span></li>
                    <li class="border-bottom my-2"></li>
                    <li class="d-flex align-items-center justify-content-between mb-4"><strong class="text-uppercase small font-weight-bold">Total</strong><span>P{{total_amount|intcomma}}</span></li>
                    <li>

                      {% comment %} <form action="#">
                        <div class="form-group mb-0">
                          <input class="form-control" type="text" placeholder="Enter your coupon">
                          <button class="btn btn-dark btn-sm btn-block" type="submit"> <i class="fas fa-gift mr-2"></i>Apply coupon</button>
                        </div>
                      </form> {% endcomment %}

                    </li>
                  </ul>

                  
                  <h5 class="text-uppercase my-5">Select Delivery Address</h5>
                  <h6 class="mb-3"><i>Your delivery address will be selected automatically based on the new address.</i></h6>
                  <form action="{% url 'store:checkout' %}" id="myform">

                    {% if delivery_addresses %}
                      {% for address in delivery_addresses %}
                        <div class="mb-3">
                        <input type="radio" name="address" value="{{address.id}}" checked> <strong>Address {{forloop.counter}}</strong> <br>
                        ( {{address.phone_number}}, {{address.barangay}}, {{address.street_name}}, {{address.landmark}} )
                        </div>
                      {% endfor %}
                      <button type="submit" class="btn btn-dark btn-lg btn-outline-dark" type="submit" onclick="confirmation();"> <i class="fas fa--sign mr-2"></i>Cash on Delivery</button>
                    {% else %}
                    <a href={% url 'store:add-address' %}>Please enter an address for the delivery location.</a>
                    {% endif %}

                    <!-- Set up a container element for the button -->
                    <div class="text-end" id="paypal-button-container"></div>

                    {% comment %} For Cash on Delivery {% endcomment %}
                   

                  </form>

                </div>
              </div>
            </div>

          </div>
        </section>
        
        {% else %}

          <div class="text-center py-5">
            <h3 class="mb-3">Your cart is empty.</h3>
            <a href="{% url 'store:home' %}"><i class="fas fa-long-arrow-alt-left mr-2"> </i>Continue shopping</a>
          </div>

        {% endif %}

      </div>
      {% endblock content %}

templates/store/index.html
{% extends 'base.html' %}
{% load static %}
      {% block content %}
      <!-- HERO SECTION-->
      <div class="container">
        <section class="hero pb-3 bg-cover bg-center d-flex align-items-center" style="background: url({% static 'images/car2.jpg' %})">
          <div class="container py-5">
            <div class="row px-4 px-lg-5">
              <div class="col-lg-6">
                <p class="text-muted small text-uppercase mb-2">NEW DISHES TO SUIT YOUR FLAVORS</p>
                <h1 class="h2 text-uppercase mb-3">Come dine with us</h1><a class="btn btn-dark" href="{% url 'store:all-categories' %}">Browse Menu</a>
              </div>
            </div>
          </div>
        </section>
        <br>
        <h1 class="h2 text-uppercase text-center mb-3">The Dev Loves Twice so much</h1>
        <section class="pt-5">
          <header class="text-center">
            <p class="small text-muted small text-uppercase mb-1">Carefully created dishes</p>
            <h2 class="h5 text-uppercase mb-4">Browse our Menu</h2>
          </header>
          <div class="row">
          {% if categories %}
            {% for category in categories %}

              <div class="col-md-4 mb-4 mb-md-0">
                <a class="category-item" href="{% url 'store:category-products' category.slug %}">
                  {% if category.category_image %}
                    <img class="img-fluid" src="{{ category.category_image.url }}" alt="{{ category.title }}">
                    {% else %}
                    <img class="img-fluid" src="{% static 'img/cat-img-1.jpg' %}" alt="{{ category.title }}">
                  {% endif %}
                  <strong class="category-item-title">{{ category.title }}</strong>
                </a>
              </div>
            
            {% endfor %}
          {% endif %}
          </div>
        </section>


        <!-- TRENDING PRODUCTS-->
        <section class="py-5">
          <header>
            <p class="small text-muted small text-uppercase mb-1">Made For You</p>
            <h2 class="h5 text-uppercase mb-4">Best Sellers in the house</h2>
          </header>
          <div class="row">

            {% if not_products %}
            {% for product in not_products %}
            
              <!-- PRODUCT-->
              <div class="col-xl-3 col-lg-4 col-sm-6">
                <div class="product text-center">
                  <div class="position-relative mb-3">

                    <div class="badge text-white badge-"></div>
                    
                    <a class="d-block" href="{% url 'store:product-detail' product.slug %}">
                      {% if product.product_image %}
                        <img class="img-fluid w-100" src="{{ product.product_image.url }}" style='filter: grayscale(100%); height: 160px;' alt="{{product.title}}">
                      {% else %}
                        <img class="img-fluid w-100" src="{% static 'images/favicon.png' %}"  alt="{{product.title}}">
                      {% endif %}
                    </a>

                    <div class="product-overlay">
                      <ul class="mb-0 list-inline">
                        <li class="list-inline-item m-0 p-0"><a class="btn btn-sm btn-outline-dark" href="#"><i class="far fa-heart"></i></a></li>
                        <li class="list-inline-item m-0 p-0">
                          {% comment %} <a class="btn btn-sm btn-dark" href="{% url 'store:add-to-cart' %}">Add to cart</a> {% endcomment %}
                            <button type="submit" class="btn btn-sm btn-dark">Not Available</button>                         
                        </li>
                      </ul>
                    </div>
                  </div>
                  <h6> <a class="reset-anchor" href="detail.html">{{ product.title }}</a></h6>
                  <p class="small text-muted">₱{{product.price}}</p>
                </div>
              </div>
            {% endfor %}
          {% endif %}

            {% if products %}
              {% for product in products %}
              
                <!-- PRODUCT-->
                <div class="col-xl-3 col-lg-4 col-sm-6">
                  <div class="product text-center">
                    <div class="position-relative mb-3">

                      <div class="badge text-white badge-"></div>
                      
                      <a class="d-block" href="{% url 'store:product-detail' product.slug %}">
                        {% if product.product_image %}
                          <img class="img-fluid w-100" src="{{ product.product_image.url }}" alt="{{product.title}}">
                        {% else %}
                          <img class="img-fluid w-100" src="{% static 'images/favicon.png' %}" alt="{{product.title}}">
                        {% endif %}
                      </a>

                      <div class="product-overlay">
                        <ul class="mb-0 list-inline">
                         
                          <li class="list-inline-item m-0 p-0">
                            {% comment %} <a class="btn btn-sm btn-dark" href="{% url 'store:add-to-cart' %}">Add to cart</a> {% endcomment %}
                            <form action="{% url 'store:add-to-favorite' %}">
                              <input type="hidden" name="prod_id" value="{{product.id}}" id="product_id">
                              <button class="btn btn-sm btn-outline-dark"><i class="far fa-heart"></i></button>
                            </form>                       
                          </li>
                        </ul>
                        &nbsp;
                        &nbsp;
                        <form action="{% url 'store:add-to-cart' %}">
                          <input type="hidden" name="prod_id" value="{{product.id}}" id="product_id">
                          <button onclick="fireSweetAlert()" type="submit" class="btn btn-sm btn-dark" >Add to Cart</button>
                        </form>   
                      </div>
                    </div>
                    <h6> <a class="reset-anchor" href="detail.html">{{ product.title }}</a></h6>
                    <p class="small text-muted">₱{{product.price}}</p>
                  </div>
                </div>
              {% endfor %}
            {% endif %}
          </div>
        </section>


        <!-- SERVICES-->
        <section class="py-5 bg-light">
          <div class="container">
            <div class="row text-center">
              <div class="col-lg-4 mb-3 mb-lg-0">
                <div class="d-inline-block">
                  <div class="media align-items-end">
                    <svg class="svg-icon svg-icon-big svg-icon-light">
                      <use xlink:href="#delivery-time-1"> </use>
                    </svg>
                    <div class="media-body text-left ml-3">
                      <h6 class="text-uppercase mb-1">Deliver in your area</h6>
                      <p class="text-small mb-0 text-muted">Allow us to prepare some time</p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-lg-4 mb-3 mb-lg-0">
                <div class="d-inline-block">
                  <div class="media align-items-end">
                    <svg class="svg-icon svg-icon-big svg-icon-light">
                      <use xlink:href="#helpline-24h-1"> </use>
                    </svg>
                    <div class="media-body text-left ml-3">
                      <h6 class="text-uppercase mb-1">Give us a call</h6>
                      <p class="text-small mb-0 text-muted">Our staffs will be glad to assist you</p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="d-inline-block">
                  <div class="media align-items-end">
                    <svg class="svg-icon svg-icon-big svg-icon-light">
                      <use xlink:href="#food-1"></use>
                    </svg>
                    <div class="media-body text-left ml-3">
                      <h6 class="text-uppercase mb-1">Well prepared dishes</h6>
                      <p class="text-small mb-0 text-muted">Dishes made from selected ingredients</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <br>
      </div>

      {% endblock content %}